### ISSUE TITLE
Maybe a typo on page 300

### ISSUE THREAD

**Issue by u5943321** [HoTT/book#1022]
On page 300, corollary 8.8.2. From the proof itself as well as the commutative diagram we can observe we are aiming to prove $ap_f$ is an equivalence. But it writes "trying to prove a mere proposition (f being an equivalence)" instead of "ap_f being an equivalence".

**Comment by mikeshulman** [comment]
Yes, I think you're right.  (It could be right to say "f being an equivalence" if the proof were organized a different way, since the overall goal is indeed to show that f is an equivalence; but since we've already said "it suffices to prove that ap_f is an equivelence", I think under the most natural reading the "current goal" at this point in the proof is that ap_f is an equivalence.)

**Comment by peterlefanulumsdaine** [comment]
closing this — seems like the commit message in 566a82d was meant to automatically do so

**Comment by peterlefanulumsdaine** [comment]
Oops, I realise that the reason this hadn’t been auto-closed was that the PR’s for the commit hadn’t been merged!  Reviewed and merged.
