### ISSUE TITLE
§2.12 maybe wrong prove step when showing decode ( x, encode ( x, p )) = p

### ISSUE THREAD

**Issue by MuseBoy** [HoTT/book#1033]
when showing $decode ( x, encode ( x, p )) = p$ in the proof of Theorem 2.12.5: $\equiv inl(refl_{a_0})$ is unnecessary and wrong.
If I am wrong, teach me please.

**Comment by mikeshulman** [comment]
I think it's right, but it means ap_inl(refl_{a_0}), according to the convention introduced in section 2.2 whereby we sometimes write ap_f(p) as simply f(p) because "generally no confusion arises".  (This is not the first instance giving the lie to the latter assertion!)  I'll update it to the more explicit notation.

**Comment by MuseBoy** [comment]
@mikeshulman yes, you are right. I forgot this convention. Thank you!
