### ISSUE TITLE
Rules for universes in Appendix A.2 are incomplete

### ISSUE THREAD

**Issue by MadeleineBirchfield** [HoTT/book#1127]
A few weeks ago I had a conversation with Carlo Angiuli regarding the lack of an $A \ \mathrm{type}$ judgment in the formal presentation of the type theory in Appendex A.2 of this book, and Carlo said that

> Yes, but there are a few awkward things about this. First, it means that the setup actually requires countably many inaccessible cardinals, which is unnecessary overkill. (We usually assume this at the start for convenience, but then one can cut down to just a few later.) The second issue is that then the colon is implicitly being indexed somewhere by a universe level, because it ranges over elements of U_i for any i (but which?). We can make sense of that by showing that every term has a unique type and thus every type has a unique universe level, but then we have to give up cumulativity! (And it’s hard to show, besides.)
> So it’s possible to make sense of that setup, but these are the reasons that type theorists prefer to have a “A type” judgment lurking in the background: it sidesteps all of this messiness with little fuss.

This implies that the rules for universes in appendix A.2 are incomplete; either there needs to be a separate judgment $A \ \mathrm{type}$ and a reflection rule 
$$\frac{A \colon U}{A \ \mathrm{type}}$$ 
or the colon needs to be indexed by $i$ and cumulativity replaced by lifting 
$$\frac{A \colon_{i} U_i}{\mathrm{Lift}(A) \colon_{i + 1} U_{i + 1}}$$

**Comment by cangiuli** [comment]
Just to clarify the context of my remarks, I was explaining the technical reasons why many authors include an `A type` judgment rather than relying on universes alone. I vote against making this change, but of course others can weigh in.

I view the role of the appendix as giving a basic outline of what a formal system for HoTT might look like; any work on the syntax or semantics of HoTT invariably makes different choices that are better suited to its purposes. In the book we do not provide any analysis of this formal system, so we have opted for a simpler presentation with fewer moving parts.

**Comment by DanGrayson** [comment]
What's the reason for adding the subscript i to the colon?

Do we state somewhere that every element has a unique type?

**Comment by mikeshulman** [comment]
I agree with Carlo: there are reasons why people actually doing concrete things with the metatheory do things differently, but that is not the purpose of the appendix, and it's not incomplete in a formal sense.
