### ISSUE TITLE
Nightly builds pdfs are dead links

### ISSUE THREAD

**Issue by Jbollenbacher** [HoTT/book#1150]
The [nightly builds](https://github.com/HoTT/book/wiki/Nightly-Builds) are all dead links, and do not contain the up-to-date PDFs.   

There are copies [here](https://homotopytypetheory.org/book/), however they do not have the same version numbers as the version number given in the nightlybuilds wiki page. 

Can we upload updated nightly build pdfs and correct the wiki links?  Thanks!

**Comment by mikeshulman** [comment]
Hmm.  Those are supposed to be compiled automatically.  It looks like maybe @favonia set up the most recent autobuild system in #1102?

**Comment by favonia** [comment]
Sorry for the trouble I might have caused... I will take a look this weekend.

**Comment by favonia** [comment]
@mikeshulman I seem to have lost write access to this repository, which made the investigation a bit challenging.

**Comment by mikeshulman** [comment]
Added!

**Comment by favonia** [comment]
@Jbollenbacher Thanks for the report. The issue is that the GitHub Actions to upload wiki pages uses `gh`, but we use a custom container with full TexLive that does not come with `gh` installed.

The current progress is that, I tried to install `gh` but the special TexLive container doesn't seem to have `sudo`? I'm pushing another commit and let's see how it goes...

**Comment by favonia** [comment]
@Jbollenbacher @mikeshulman After some hacking I believe it works. Please check.

**Comment by mikeshulman** [comment]
Looks good to me!  Thanks.  Does it work for you too, @Jbollenbacher ?

**Comment by Jbollenbacher** [comment]
Looks good now, thanks all
