### ISSUE TITLE
Lemma 4.7.3 multiple bugs

### ISSUE THREAD

**Issue by gluttonousGrandma** [HoTT/book#451]
In the proof of Lemma 4.7.3
"\varphi_b(a,p) & \defeq \pairr{s(a),s'(p)\ct L(a)}"
should be 
"\varphi_b(a,p) & \defeq \pairr{s(a),L(a)\ct s'(p)}",
and
"\psi_b(x,q) &\defeq \pairr{r(x),R'(b)\ct r'(q)\ct K(x)"
should be
"\psi_b(x,q) &\defeq \pairr{r(x),K(x)\ct r'(q)\ct R'(b)".

Also, in 
"\prd{b:B}{a:A}{p:f(a)=b} \psi_b(\varphi_b({a,p}))= \pairr{a,p}."
p should have type g(a)=b, not f(a)=b.

I can't follow the proof in its current form, please fix it.

**Comment by bobiopen** [comment]
In Lemma 4.7.3, I stuck in the part "applying lemma 3.11.9" .  I think it should be path induction.

**Comment by mikeshulman** [comment]
The exact statement we need is equation (2.15.10).  This follows from the "dependent currying" equivalence (2.15.9), the fact that based path spaces are contractible, and the statement that if A is contractible with center a, then $\Pi_{(x:A)} P(x)$ is equivalent to $P(a)$.  The latter looks a bit like 3.11.9 but for $\Pi$-types rather than $\Sigma$-types, which is probably why it was referred to, although I agree that it's not really a "version" of 3.11.9.

I'm not sure if 2.15.10 is ever proven explicitly in the book; can anyone find it?  If not, perhaps we should add it as an exercise to chapter 2 or 3, and refer to it from 4.7.3.

**Comment by bobiopen** [comment]
Thanks for your attention.&nbsp;
Now, I understand it's just a modified statement of Lemma 3.11.9 . Given an element of $P(a)$ where $a$ is the center of $A$, we can construct an element of $\Pi_{(x:A)}P(x)$ by transporting. And the part we discussed in Lemma 4.7.3 follows by Exercise 2.10, Lemma 3.11.8 and the previous statement. 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HoTT/book"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 凌晨5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HoTT/book] Lemma 4.7.3 multiple bugs (#451)





 
The exact statement we need is equation (2.15.10).  This follows from the "dependent currying" equivalence (2.15.9), the fact that based path spaces are contractible, and the statement that if A is contractible with center a, then $\Pi_{(x:A)} P(x)$ is equivalent to $P(a)$.  The latter looks a bit like 3.11.9 but for $\Pi$-types rather than $\Sigma$-types, which is probably why it was referred to, although I agree that it's not really a "version" of 3.11.9.
 
I'm not sure if 2.15.10 is ever proven explicitly in the book; can anyone find it?  If not, perhaps we should add it as an exercise to chapter 2 or 3, and refer to it from 4.7.3.
