### ISSUE TITLE
Linebreaks

### ISSUE THREAD

**Issue by vladimirias** [HoTT/book#777]
Let's run the files of the book through some program that will introduce 
linebreaks making all lines no longer than 100 characters. 
This will make it much more convenient to look at files in GitHub. 

The only possible complication that I can see now is with the lines that start with % which are considered a comment - these will need to have % introduced after each linebreak. 

Can someone write a program to do it? Jason?

**Comment by mikeshulman** [comment]
I have good reasons for breaking lines in between sentences only: git diffs work on a line-by-line basis that is adapted for code, whereas in text the basic unit is not the line but the sentence.

**Comment by mikeshulman** [comment]
There is something you can do with the Stylish add-on that makes github wrap long text lines so you don't have to scroll to the right.  I've forgotten it at the moment but I'll try to remember to look it up sometime.

**Comment by andrejbauer** [comment]
I am annoyed by the long lines as well but I learned to live with them because so many people wanted them.

**Comment by mikeshulman** [comment]
Changing them at this point would also introduce a lot of churn and mess up git-blame output.  However, if there were a consensus that it was worth it, we could; I think the main things I care about are that there is a line break after each sentence-ending period and that paragraphs don't get "re-flowed" all the time, since that is what really breaks the diffs.
