### ISSUE TITLE
Theorem 10.5.8(vi) proof

### ISSUE THREAD

**Issue by jamescheney** [HoTT/book#794]
In the proof of part (vi) of theorem 10.5.8, the passage 

[u] \rightarrowtail V and [u] \rightarrowtail V

should (I think) be
[u] \rightarrowtail V and [u] \rightarrowtail V

that is, the second [u] should be a [v].

This is in version first-edition-611-ga1a258c.

**Comment by mikeshulman** [comment]
Already fixed in 706-ged2c765.

**Comment by jamescheney** [comment]
Sorry, I was assuming that the version here:
http://hottheory.files.wordpress.com/2013/03/hott-online-611-ga1a258c.pdf
was the latest version, I'll check my other issue to see if it is fixed already too.

**Comment by mikeshulman** [comment]
Not an unreasonable assumption!  We're many months delinquent on updating the posted version at the moment; I've been hoping that some of the open pull requests will get merged before going ahead with that.

**Comment by jamescheney** [comment]
That's understandable - I just wasn't sure where to look for the really-current version (other than cloning and building which I didn't feel up to)

**Comment by mikeshulman** [comment]
Yeah, you may have to clone and build to get the up-to-date version.

**Comment by pthariensflame** [comment]
@jamescheney @mikeshulman I keep a clone of the repo locally that I rebuild all PDFs from whenever the repo changes (I pull from master pretty much every day).  If I posted the PDFs somewhere, would that be helpful to people?

**Comment by mikeshulman** [comment]
I expect we could probably configure Travis to update a "nightly build" automatically and post it somewhere, but I don't know how to do that.

**Comment by pthariensflame** [comment]
Nor do I.  :(

**Comment by jamescheney** [comment]
I did read the "guidelines for contributing", and they didn't say anything about how to write a lightweight issue to highlight a typo (which is what I wanted to do) rather than constructing a pull request.  Maybe just adding a paragraph stating the best practice for the lightweight case (and clarifying that there is currently no archived "nightly build" so the best way to be sure is to clone and build)?

**Comment by mikeshulman** [comment]
The difference between pull requests and issues is not one of light- vs heavy-weight.  An issue just points out a problem, whereas a pull request proposes a specific fix.  I think the "guidelines for contributing" don't consider merely opening an issue to be "contributing" (since it doesn't actually involve editing the source), so it doesn't give any instructions about it -- but perhaps it should!

**Comment by pthariensflame** [comment]
@mikeshulman [Here is some documentation about getting Travis to release (some of) its builds automatically.](http://docs.travis-ci.com/user/deployment/releases/)  It seems like you'll need to generate the token(s) yourself (since you're the official "owner" of this repo), but it doesn't actually seem that complicated.

**Comment by andrejbauer** [comment]
We already have Travis hooked up to the book. With just a bit of work we could then always have the latest version available on the web page.
