### ISSUE TITLE
Path induction, possible typo

### ISSUE THREAD

**Issue by amithogadi** [HoTT/book#870]
On page 49, line 2, in the book, C should be of the from 
C: \Sum_{x,y:A} (x=_Ay) \to U
instead of 
C: \Pi_{x,y:A}(x=_A y) \to U
This is because we need C to be a function of three variables C(x,y,p) and not function of dependent functions as written. 
This is also repeated further in the book. 
Please let me know if I am missing something.

**Comment by andrejbauer** [comment]
When referring to text, please give section and subsection number. Page numbers are not reliable as different versions of the book have different page numbering.

**Comment by andrejbauer** [comment]
But to answer your question: the types (∑(x,y:A) x = y) → U and ∏(x,y:A) (x = y → U) are equivalent. The book says that C takes one argument which is a dependent triple (x, y, p), while you are suggesting that it should take three arguments x, y, and p.

In functional programming the difference between the two options would be visible, as we would write C(x,y,p) in one case and C x y p in the other. But the book uses a convention (presumably because mathematicians are confused by functional programming) to write C x y p inaccurately as C(x,y,p). Is this the problem that bothers you?

**Comment by amithogadi** [comment]
Thanks.
I misunderstood
[image: \Pi(x,y:A) (x=y)\to U] as [image: (\Pi(x,y:A)(x=y)) \to U]

**Comment by andrejbauer** [comment]
Ah yes, the rule to remember is that "pies and sigmas gobble up as much as they can".
