### ISSUE TITLE
inconsistent use of hyphen in "path-constructor"

### ISSUE THREAD

**Issue by nicolaikraus** [HoTT/book#882]
"Path-constructor" is sometimes written with a hyphen and sometimes without. Which variant is better?

**Comment by mikeshulman** [comment]
I'm not sure which is better from an English-language standpoint; anyone have an opinion?  But "path constructor" appears much more often in the book than "path-constructor", so it would be less work to standardize on the former.

**Comment by pthariensflame** [comment]
I think the version without the hyphen is "more correct" grammatically speaking.

**Comment by pthariensflame** [comment]
On the other hand:  http://grammarbook.com/punctuation-rules/hyphens.aspx

**Comment by mikeshulman** [comment]
That link is broken for me.

**Comment by pthariensflame** [comment]
Because I edited it after it was posted.  Click the newest version (or just put "www." in front of the old one).

**Comment by mikeshulman** [comment]
Are you pointing to rule 2b at that link?

**Comment by pthariensflame** [comment]
Yeah.  I don't think there's any way that the words “path” and “constructor,” in that order, would have an ambiguous referant.

**Comment by mikeshulman** [comment]
FWIW: https://www.google.com/search?q=%22path+constructor%22

**Comment by pthariensflame** [comment]
Ah.  All of those seem to be referring to a constructor [(in the object-oriented sense)](https://en.wikipedia.org/wiki/Constructor_\(object-oriented_programming\)) that happens to be named `Path`.  I don't think that kind of meaning would be particularly relevant to the HoTT book.  :)

**Comment by mikeshulman** [comment]
Right.

**Comment by nicolaikraus** [comment]
So, I guess it does not really matter, and there seems to be a slight preference for "path constructor"? I will make a pull request to make it consistent (but not immediately, on the weekend or so).

**Comment by martinescardo** [comment]
I think it does matter.

If I say my car maker is reckless because it ignored carbon-emission
regulations, I was both right not to write "car-marker" or "carbon
emission". However, it is both true, and syntactically/grammatically
correct to say that a current car-maker nightmare is have ignored the
problem of carbon emission.

Martin

On 13/01/16 21:21, Nicolai Kraus wrote:
> So, I guess it does not really matter, and there seems to be a slight
> preference for "path constructor"? I will make a pull request to make it
> consistent (but not immediately, on the weekend or so).
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HoTT/book/issues/882#issuecomment-171436915>.
> 

-- 
Martin Escardo
http://www.cs.bham.ac.uk/~mhe

**Comment by martinescardo** [comment]
Oh, dear. Add [to].

If I say my car maker is reckless because it ignored carbon-emission
regulations, I was both right not to write "car-marker" or "carbon
emission". However, it is both true, and syntactically/grammatically
correct to say that a current car-maker nightmare is [to] have ignored
the problem of carbon emission.

M/

On 13/01/16 21:34, Martin Escardo wrote:
> I think it does matter.
> 
> If I say my car maker is reckless because it ignored carbon-emission
> regulations, I was both right not to write "car-marker" or "carbon
> emission". However, it is both true, and syntactically/grammatically
> correct to say that a current car-maker nightmare is have ignored the
> problem of carbon emission.
> 
> Martin
> 
> On 13/01/16 21:21, Nicolai Kraus wrote:
>> So, I guess it does not really matter, and there seems to be a slight
>> preference for "path constructor"? I will make a pull request to make it
>> consistent (but not immediately, on the weekend or so).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HoTT/book/issues/882#issuecomment-171436915>.
>>
> 

-- 
Martin Escardo
http://www.cs.bham.ac.uk/~mhe

**Comment by mikeshulman** [comment]
If "path-constructor" is ever used as a noun adjunct, it should definitely
be hyphenated then.  It's less obvious that it should not be hyphenated in
other cases, but that does seem to be the preference.

**Comment by martinescardo** [comment]
As another example, I worked in real-number computation in the past. I
wouldn't be wrong to say that I worked in real number computation,
although a number of people would insist that hyphen bewteen "real" and
"number" is a must. But nobody would call the real numbers real-numbers,
for instance saying "let R be the set of real-numbers".

I like this book: Steven Pinker. The sense of style.
http://stevenpinker.com/publications/sense-style-thinking-persons-guide-writing-21st-century

Not because I have learned from it, but because it confirms my
preconceptions. :-)

Martin


On 13/01/16 21:40, Mike Shulman wrote:
> If "path-constructor" is ever used as a noun adjunct, it should definitely
> be hyphenated then. It's less obvious that it should not be hyphenated in
> other cases, but that does seem to be the preference.
> 
> On Wed, Jan 13, 2016 at 1:37 PM, Martin Escardo <notifications@github.com>
> wrote:
> 
>> Oh, dear. Add [to].
>>
>> If I say my car maker is reckless because it ignored carbon-emission
>> regulations, I was both right not to write "car-marker" or "carbon
>> emission". However, it is both true, and syntactically/grammatically
>> correct to say that a current car-maker nightmare is [to] have ignored
>> the problem of carbon emission.
>>
>> M/
>>
>>
>> On 13/01/16 21:34, Martin Escardo wrote:
>> > I think it does matter.
>> >
>> > If I say my car maker is reckless because it ignored carbon-emission
>> > regulations, I was both right not to write "car-marker" or "carbon
>> > emission". However, it is both true, and syntactically/grammatically
>> > correct to say that a current car-maker nightmare is have ignored the
>> > problem of carbon emission.
>> >
>> > Martin
>> >
>> > On 13/01/16 21:21, Nicolai Kraus wrote:
>> >> So, I guess it does not really matter, and there seems to be a slight
>> >> preference for "path constructor"? I will make a pull request to
> make it
>> >> consistent (but not immediately, on the weekend or so).
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >> <https://github.com/HoTT/book/issues/882#issuecomment-171436915>.
>> >>
>> >
>>
>> --
>> Martin Escardo
>> http://www.cs.bham.ac.uk/~mhe
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HoTT/book/issues/882#issuecomment-171442426>.
>>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HoTT/book/issues/882#issuecomment-171443166>.
> 

-- 
Martin Escardo
http://www.cs.bham.ac.uk/~mhe

**Comment by nicolaikraus** [comment]
Nice examples! But I guess all you mean is that I should have said "it does not matter for all occurrences in the book" [I will check that] instead of "it does not really matter"?
