### ISSUE TITLE
Link to pdf for on screen viewing (and the other hott book links on website) down

### ISSUE THREAD

**Issue by peter-campora** [HoTT/book#896]
I get a 404 when trying to use this link https://hott.github.io/book/nightly/hott-online-1025-g804e157.pdf
Wasn't sure if this should be posted here or if there was some other way.

**Comment by mikeshulman** [comment]
This particular problem is fixed now.  Well, the URL you included above won't (ever) work, but the links from https://homotopytypetheory.org/book/ do work, because I manually ran the script that updates the redirects from there to the correct URLs.

However, the problem will recur (and persist for up to 24 hours) every time the book is updated, until we fix #846 (or find some other way to deal with the problem).  Would anyone care to try merging #880 so we can see whether that does the trick?

**Comment by peter-campora** [comment]
Ok, thanks! I should have posted the link address instead (my bad), but thanks again for the update.
