### ISSUE TITLE
"R_c-induction" can *only* show mere propositions 

### ISSUE THREAD

**Issue by nicolaikraus** [HoTT/book#897]
Just before Lemma 11.3.8, it says: 
"In particular, if $A$ is a mere property, the third hypothesis in $\RC$-induction is trivial."
I would suggest to replace this by:
"Note that the third hypothesis in $\RC$-induction is fulfilled exactly if $A$ is a mere proposition."
(I would find "... if $A$ is a family of mere propositions" even better, but that's not my point.)
I.e.: What is currently missing is the observation that R_c-induction (which is defined to be a special case of the general principle) can directly only show families of propositions, not general families.

**Comment by mikeshulman** [comment]
It's true that the third hypothesis of $\RC$-induction is equivalent to saying that $A$ is a family of mere propositions (this is what "mere property" means) --- but unless I am confused, that equivalence depends on Lemma 11.3.8, which is proved by $\RC$-induction, and also on Theorem 11.3.9 which follows from it.  Until we have these, we don't know that paths in A(u) for a fixed u are a special case of the dependent paths appearing in the statement of $\RC$-induction, since we don't know that refl(u) can be written as eq_{\RC}(u,u).

So I agree that this should be mentioned, but the wording is a bit more complicated.

**Comment by nicolaikraus** [comment]
> that equivalence depends on Lemma 11.3.8, which is proved by $\RC$-induction, and also on Theorem 11.3.9 which follows from it

Right, this observation needs Lemma 11.3.8. I don't think it needs Theorem 11.3.9 though:
Fix `u : R_c`. From Lemma 11.3.8, we get `p : u ~ u`. The third hypothesis implies that, for `a, b : A(u)`, we get `transport (eq(u,u) , a) = a` and `transport (eq(u,u) , a) = b`, thus `a = b`.

> this is what "mere property" means

I guess I copied without reading, I thought it said "mere proposition". I take back my comment in parentheses.

> So I agree that this should be mentioned, but the wording is a bit more complicated.

You are right. We could either add an explanation after 11.3.8, possibly with a proof sketch, or we could remark it just before 11.3.8, or we could add an exercise and give a reference to that exercise just before 11.3.8.

**Comment by mikeshulman** [comment]
How about changing "In particular, if $A$ is a mere property, the third hypothesis in $\RC$-induction is trivial" to "Note that the third hypothesis in $\RC$-induction is automatic if $A$ being a mere property (we will see in a moment that it is in fact equivalent to this)." and then including the short argument right after 11.3.8?

Would you like to make a pull request?

**Comment by nicolaikraus** [comment]
Ok, sure!
