### ISSUE TITLE
Suggestion of an exercise about connectedness

### ISSUE THREAD

**Issue by koba-e964** [HoTT/book#920]
How about adding an exercise about connectedness like:
Assuming LEM, show that types are connected if and only if they are categorically connected, i.e. for every $A: \type$ we have

```
\iscontr(\trunc 0{A}) \eqvsym ((\prd{B,C: \type} (A \to B) + (A \to C) \eqvsym (A \to B + C)).
```

? (The definition of categorical connectedness is from [nLab](https://ncatlab.org/nlab/show/connected+space).)

I believe I obtained this result assuming LEM, but I don't know whether LEM is necessary or not. In addition, I think propositional resizing is necessary to avoid universe problems (the right-hand side is in the next higher universe than A, B and C). 

If we add this, I think it is appropriate to add it to Chapter 7's Exercises.

**Comment by mikeshulman** [comment]
Surely that can't be right as written, because the LHS is a mere proposition, but the RHS isn't.  The nLab definition would have on the right "the canonically defined function `(A\to B)+(A\to C) \to (A \to B+C)` is an equivalence."

I'm pretty sure that the left-to-right direction does not require LEM.  Something closely related is in the HoTT/Coq repository [here](https://github.com/HoTT/HoTT/blob/master/theories/HIT/Connectedness.v#L129).  I don't see why propositional resizing would ever be needed either; the RHS may live in a larger universe, but there's nothing wrong with two types in different universes being equivalent to each other.

I think that the right-to-left implication (for all types A) is actually *equivalent* to LEM: let A be the suspension of a proposition P such that `\neg \neg P` is true.

In any case, yes, I think this is a good exercise -- perhaps with several parts to explore all these aspects.

**Comment by koba-e964** [comment]
Thanks. I confirmed that left-to-right implication doesn't require LEM, and that right-to-left implication (forall A) is equivalent to LEM, by your argument.

The correct statement would be like:
Assuming LEM, show that types are connected if and only if they are categorically connected, i.e. for every $A: \type$ we have
```
\iscontr(\trunc 0{A}) \eqvsym (\prd{B,C: \type} \isequiv(e_{A,B,C})),
```
where $e_{A,B,C}: (A \to B) + (A \to C) \to A \to B + C$ is canonically defined by
```
e_{A,B,C}(\inl(g)) \defeq \lam{x} \inl(g(x)),
e_{A,B,C}(\inr(g)) \defeq \lam{x} \inr(g(x)).
```
Is it ok?

**Comment by mikeshulman** [comment]
I would probably state it as "(a) Show that any connected type is categorically connected, (b) show that all categorically connected types are connected if and only if LEM holds".

**Comment by koba-e964** [comment]
I see.
By the way, does this change have to wait for 2nd edition, or can it be done in 1st edition?

**Comment by mikeshulman** [comment]
Adding exercises (at the end of the list, so it doesn't change any numbering) can be done in 1st edition.
