### ISSUE TITLE
Update Lulu paperback version

### ISSUE THREAD

**Issue by osense** [HoTT/book#939]
Hello,

I would like to order a paperback copy of the book from Lulu and I noticed that the version available there is **1005** whereas the nightly builds are on **1075**. I don't know how significant are the changes between those versions, but if someone could update the version on Lulu I'd feel better about the whole thing. :)

Thank you.

**Comment by Laviebelle** [comment]
Do you can indica﻿⊥e me wich is ⊥he ⊥i⊥le oF ⊥he book in ques⊥ion please?

**Comment by andrejbauer** [comment]
I'll do it tomorrow or at the latest on Thursday if you can wait that long.

**Comment by osense** [comment]
Sure, no problem — I can wait that long ;)

**Comment by andrejbauer** [comment]
It took a bit longer than two days, I hope you weren't holding your breath. Both versions have been updated to 1104.

**Comment by osense** [comment]
Thanks! Looking forward to receiving my copy.

**Comment by GeoffChurch** [comment]
I placed my order for the paperback copy ten days ago (28 December 2020) and received a copy with version `first-edition-1174-g29279f5`, corresponding I guess to [this commit](https://github.com/HoTT/book/commit/29279f5d00f1fdb013d5c7fbe804b49cb25e61b1) from 19 April 2018. The online pdfs are currently up-to-date with the [most recent commit](https://github.com/HoTT/book/commit/d98a32f95e1858e1b619cae02f643334f2ce9022) (version `first-edition-1274-gd98a32f`).

I don't see anything on Lulu mentioning which version is currently being shipped. Can this please be updated again, and maybe we can have the current version/date be part of the book's description on Lulu so that buyers can cross-reference before purchase?

**Comment by mikeshulman** [comment]
Thanks for the heads-up, and sorry about this!  The lulu version has now been updated (unfortunately this has to be done manually), and the [book page](https://homotopytypetheory.org/book/) now includes the information of which version is available from lulu.  Thanks Andrej!
