### ISSUE TITLE
Technical error in first sentence of section 1.9

### ISSUE THREAD

**Issue by JakeEhrlich** [HoTT/book#946]
The first sentence of section 1.9 states "The rules we have introduced so far do not allow us to construct any infinite types" which is technically speaking invalid. For instance the type \prod_{A:\mathcal{U}} (A -> A) -> (A -> A) can be constructed after section 1.4. Micheal Shulman pointed out to me that even the first universe has infinitely many inhabitants so there are even simpler examples. Perhaps this should be reworded to something like "The rules introduced so far do not allow us to construct any natural examples of infinite types" or something like that? I'm not sure what would best replace the sentence.

**Comment by mikeshulman** [comment]
I'm not sure what remains of the problematic sentence to be saved.  Certainly one can argue that the universe is a "natural" example of an (infinite) type!  Perhaps the real point that should be made to introduce this section is that what we need for developing mathematics is specifically *the natural numbers*, rather than "an infinite type".

(Possibly relevant is that we now know it's possible to actually construct the natural numbers from the universe if we have propositional resizing -- although prop resizing is not mentioned in the book until chapter 3.)
