### ISSUE TITLE
Wrong definition for the return type at paragraph 5.3

### ISSUE THREAD

**Issue by francoisthire** [HoTT/book#965]
At paragraph 5.3, I think the definition for C while defining the function _double_ using W-types is wrong, a lambda is missing. Instead, it should be

\lambda a^{2}.
\Pi f^{B(a) -> Nw}.
\Pi g^{B(a) -> Nw}.
Nw

At least in my formalization, I have to. Otherwise, while defining e_1 as 

lambda f.
lambda g.
succW (succW (g (star)))

won't be well-typed since e_1 needs to compute B(1) so that g(star) is well-typed. Thus, I have the impression that using rec2 as defined in paragraph 1.8 cannot work here.

**Comment by kristinas** [comment]
Hi,

Thanks for your question. C is meant to be a shorthand for the given 
type, to be inserted as-is into the bigger formula, not a separate 
definition. If you want to declare it as a separate definition then you 
are right, you need to parameterize it over the variables appearing in 
it (in this case a).

Best,

Kristina

**Comment by mikeshulman** [comment]
I think @francoisthire 's first point is that since C depends on a (however that dependence is indicated), we can't use rec_2, we have to use ind_2.  I think I agree with this.  The next point is that our definition of ind_2 in section 1.8 takes a *function* C:2->U as its first argument, so that to be correct the C here must be defined to be a function.  I think I agree with that too.

**Comment by mikeshulman** [comment]
I think @francoisthire 's first point is that since C depends on a (however that dependence is indicated), we can't use rec_2, we have to use ind_2.  I think I agree with this.  The next point is that our definition of ind_2 in section 1.8 takes a *function* C:2->U as its first argument, so that to be correct the C here must be defined to be a function.  I think I agree with that too.
