### ISSUE TITLE
Tagalog Localization/Translation

### ISSUE THREAD

**Issue by themarshann** [HoTT/book#976]
Hi, I'd like to contribute to this project by translating it into Tagalog. Hope it'll be okay for me to do so.
Thanks!

**Comment by mikeshulman** [comment]
Is there a reason why we suddenly have many people asking to translate the book into different languages at the same time (@Santu41, @dbucci24, @jbeguna04)?  Is there a thread somewhere else on the Internet right now that's talking about translating the HoTT Book?

I will give the same answer here that I gave to the others, although this is once again only my opinion as *one* of the authors and no one else has yet weighed in.  My opinion is that translations are great, and should be done in separate forks or projects so that responsibility for them clearly lies with the translator rather than the original authors.

**Comment by themarshann** [comment]
I'm not so sure, but perhaps, we're sort of on the same _group_ looking for open source projects we can contribute to. Translating seems to be the least technical contribution to which we can impart our skill, hence, the sudden _influx_ of individuals wanting to translate.

And I do understand your point. Thanks for the feedback. :)
I've forked this project [here](https://github.com/themarshann/book-tl)
