### ISSUE TITLE
Include eta-conversion in A.1

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/book#995]
Jugmental eta-conversion for functions (which is assumed in the main body of the text) seems to be missing from the first presentation of syntax in appendix A.1?  If it's there, it's so cleverly hidden that I can't see it.

**Comment by awodey** [comment]
how did that go so long without being noticed?!

**Comment by mikeshulman** [comment]
Maybe nobody actually reads A.1?

**Comment by cangiuli** [comment]
It's not totally clear to me whether judgmental eta fits in the story of A.1, which seems to be that definitional equality is simply untyped(?) convertibility generated by beta-like rules. (This is discussed right above A.1.1.) If we add judgmental eta, we would at least need to clarify positively that the convertibility relation is typed, and indicate as such in the notation.

(On the other hand, I'm also not clear how to present HoTT-Book-style HITs in the story of A.1, since their elimination rules don't quite fit the style of "defining equations", so maybe we can just be a bit vague about the eta rule.)

**Comment by mikeshulman** [comment]
That's true, eta rules only make sense for typed equality.  I suppose another alternative would be to just say explicitly that the system in A.1 *doesn't* include eta rules (diverging from the rest of the book).

In some sense, the real question is what is the purpose of A.1, which is something I never really understood.

**Comment by cangiuli** [comment]
I agree completely. For the first edition, I think it would be best to just add a remark about the lack of eta, as you suggest.

**Comment by fpvandoorn** [comment]
Why do eta rules only make sense for typed equality? Couldn't you add an untyped eta-reduction rule 
```
λx. f(x) ↓ f
```
and say that the convertibility relation ` ↓ ` is generated by beta, eta and the defining equations for constants?

**Comment by mikeshulman** [comment]
I don't understand the details, but untyped eta certainly leads to well-typed terms that are convertible with ill-typed ones, like

```
λx. 3(x) ↓ 3
```

I'm not sure whether you could set things up so that this isn't a problem.  I do know that people generally only talk about eta rules that are type-sensitive, so I expect that it's at least not easy.

**Comment by mikeshulman** [comment]
Okay, I'm out of my league.  There must be *some* reason people usually do it this way.  Can anyone help?

**Comment by mikeshulman** [comment]
I guess one annoying thing about eta-reduction is that it's only valid when `x` is not free in `f`.  I think that makes it "non-local" in a way that's different from all other reduction rules.

**Comment by jonsterling** [comment]
I hope that I can offer some help in understanding the situation with eta rules, reductions, etc. from a type theorist's perspective.

While it is possible to think of the eta rule for pi types or function types as part of a reduction relation (I believe that this does work, for the reason that @fpvandoorn has explained), this is generally looked down upon by type theorists for two classes of reason:

1. The side conditions for the reduction are very strange and unnatural (as Mike says, you check whether a variable is free, which is a bizarre rule). This doesn't mean it doesn't work, but it's a sign that one should turn back---side conditions like this, as a rule of thumb, pretty much always means you've got something backwards in your formulation, even if it works.

2. The more important reason is that the reduction-based approach does not scale up nicely to other type-theoretic connectives; it's almost a coincidence that it worked for pi types. Generally, eta is not just something you do only for the pi types, but is actually a property we demand of all the *negative* type connectives (in terms of polarity), most notably *sigma types*. Back in the old days when people wanted to think of type theory in terms of rewriting, this eta rule was known as "surjective pairing".

The problem with achieving the sigma eta rule / surjective pairing using reduction is that such a reduction relation is not confluent, at least if you formulate it in the obvious way. Now, I am aware that there are likely ways around this technical problem, but I want to suggest that it is better to cure the disease (generating definitional equivalence from untyped rewriting) than the symptom (non-confluence of naive eta rule for sigma types). In any case, the typed definitional equivalence is much closer to the abstract denotational models of type theory than the rewriting style, so it seems like we could at least get many of the people around here to agree with it. 😄 

In order to achieve a clean development of full Martin-Loef type theory which supports the necessary unicity principles for the negative type connectives (at least pi and sigma), a more abstract approach is demanded (or at least suggested), arising naturally from the *typed* definitional equivalence adopted by Per Martin-Loef in the 1980s, bringing type theory into harmony with the structural style of mathematics (for instance, the tradition of Lawvere).

[It's worth clarifying that the system known as MLTT has typed rather than untyped definitional equivalence, so if the HoTT book formalism is intended to be an extension of MLTT, it should be clarified that definitional equivalence is typed (even if the types are omitted in the notation, which is a fine convention).]

Today, type theorists operationalize the typed definitional equivalence using a reduction-free form of calculation, called "normalization by evaluation" (and called many other things too). In the context of type theories as languages for formal proof or as algebraic gadgets, we found over the past 30 years of struggle that simply abandoning the untyped rewriting perspective and replacing it with something more abstract (and typed) made many things more simple, and brought us into closer harmony with the denotational models we wished to characterize.

**Comment by jonsterling** [comment]
> Thanks! Can you give (a pointer to) an example of the non-confluence of surjective pairing?

Here's a good place to look: https://www.cambridge.org/core/journals/journal-of-functional-programming/article/theoretical-pearl-yet-yet-a-counterexample-for-sp/9C225C5A15E450FA268A2BA476622598. Note that this example is for typed lambda calculus extended with a recursion operator; I don't know what the proper source for dependent type theory would be, or if that's even been worked out. Hopefully someone who knows more about the rewriting world can chime in and clarify.

Let me just reiterate, by the way, that there are ways around this problem (as Curien has shown in several papers), so it shouldn't be taken as a no-go result. Just an indicator that the rewriting approach is extremely complicated in comparison to typed definitional equivalence, and that culturally, people coming from the perspective of untyped conversion have generally not attempted to include eta rules in their systems. (For instance, it is only fairly recent that Coq has had support for eta conversion, whereas Agda has always had about as much eta as anyone can handle.)

------------------

> And where is the best place to learn about NBE?

This is a little tricky question to answer, because NbE has been invented again and again in different contexts, and was always a little different each time (sometimes cosmetically, other times substantially). The first instance of NbE occurs in Martin-Loef's proof of decidability of definitional equivalence for his original version of intuitionistic type theory, and bears a resemblance to a constructive version of the gluing models.

From a mathematical point of view, the clearest "just the punchline" explanation of what is happening in NBE can be found in Streicher's note, [Categorical Intuitions Underlying Semantic Normalisation Proofs](cs.au.dk/~nbe98/Proceedings/thomas-streicher.ps); to get more details, I would recommend studying the following papers:

1. Fiore. *Semantic analysis of normalisation by evaluation for typed lambda calculus.*
2. Altenkirch, Hofmann, Streicher. *Categorical reconstruction of a reduction free normalization proof.*
3. Čubrić, Dybjer, Scott. *Normalization and the Yoneda embedding.*

Additionally, the ideas also appear (in a slightly hidden way) in Paul Taylor's book, *Practical Foundations of Mathematics* when he discusses gluing and completeness, IIRC. Finally, one of the fruits of my summer at Aarhus was the following notes I compiled while we were studying and working to understand Marcelo's paper which I mentioned above:

Sterling, Spitters. [Normalization by gluing for free lambda-theories](http://www.jonmsterling.com/pdfs/gluing-note.pdf)


It has not yet appeared in the literature how to extend these semantic techniques to normalization results (and thence decidability typed definitional equivalence) for dependent type theory, but as of fairly recently I have become aware of the broad strokes of how to do it. But I don't want to step on anybody's toes for now, so I'll leave it at that.

In the context of dependent type theory, most type theorists employ a method which we might call "freestyle NbE", which is a very computer-science-style way to do the proofs without worrying too much about the mathematical or categorical infrastructure (think "reducibility proofs without the reduction")---it's the state of the art, and scales remarkably well to increasingly complicated systems, but we are aware that it is not perhaps the end goal. If you have the patience for dealing with gnarly stuff about syntax (which we computer scientists love, perhaps a bit too much), I really recommend studying Andreas Abel's habilitationsschrift, which I found extremely useful:

Abel. [Normalization by Evaluation: Dependent Types and Impredicativity](http://www.cse.chalmers.se/~abela/habil.pdf)

**Comment by mikeshulman** [comment]
Wow, that note that you wrote with Bas is mind-blowing.  It will take me a long time to really internalize it.  I have so many questions I want to ask about it, but probably this is not the right forum.  (-:

Maybe just one: in terms of actually implementing a normalization for a type theory, it seems as though NbE as described there requires the semantic/metatheory to have all the same structure as the object language, so that it passes to the gluing model.  But we can surely also implement (say) dependent type theory, or cubical type theory, inside an ordinary simply typed programming language.  Is this related to "freestyle NbE"?

**Comment by jonsterling** [comment]
@mikeshulman I'm glad it provoked some questions :) Feel free to email me any time! Yes, my current understanding is that "freestyle NbE" can be thought of as you say. (which is what is described in Abel's thesis, and is much closer to what you must actually implement -- for instance, it is how we have implemented the `redtt` proof assistant for cartesian cubical type theory). I would say (very a-historically) that freestyle version is based on the observation that the things you're doing in an operational sense don't require all that structure, but somehow you must use all that structure to see that it is correct.

That's why in the correctness proofs for freestyle NbE there is this strange fact that the thing which looks like gluing (the logical relations model) is only used in one part, whereas in the mathematical style of NbE it is kind of everywhere.

**Comment by peterlefanulumsdaine** [comment]
It seems this issue was resolved in c8681b6, and should be closed.  But this was a fascinating thread to read, and I’m reluctant to hide it from (I guess) the main place it’s currently discoverable.    Is there anywhere it’d make sense to link it, so that it doesn’t get forgotten forever once closed?

**Comment by DanGrayson** [comment]
A new page on the wiki might be a good place for a link to it.

**Comment by mikeshulman** [comment]
What about copying it to a section of https://ncatlab.org/nlab/show/eta-conversion ?

**Comment by JasonGross** [comment]
I just saw this, and want to note that eta contraction breaks well typedness of terms if you have cumulativity for universes but not function types.  Consider
```coq
Universe u.
Constraint Set < u.
Axiom prod : Type@{u} -> Type@{u} -> Type@{u}.
Axiom F : (Set -> Set -> Type@{u}) -> Type@{u}.
```
and then taking `F (fun x y : Set => prod x y)`.  This is valid when you have only cumulativity of universes.  But if you eta-contract, then you have `F prod`, and this is only valid when you have cumulativity for Pi types as well as universes.

**Comment by jonsterling** [comment]
I like to think of Jason's example is maybe more of an explanation of why type theory should be algebraic, rather than an indictment of eta contraction ;-) There is a tension between the idea of definitional equivalence as "a relation on raw terms that we have to check preserves type" and definitional equivalence as the collection of equations that hold on the nose in a given type theory (in which, obviously, one only considers equations whose both sides are well-typed!).

In 2020 it is easy to resolve the apparent contradiction by seeing the former as an implementation strategy (that can be used in some very specific circumstances), and the latter as the actual "type theoretic" thing. But this understanding was hard-won, and would be foreign to many people who studied type theory 20 years ago, and even to some people who study it today 😉 

If cumulativity is dealt with correctly (as a property of the surface language and not the type theory, elaborated to coherent coercions), then the problem that Jason correctly raises is resolved.

**Comment by jonsterling** [comment]
@JasonGross Ah that is a shame! I do not have a copy, but I have written to Thomas to see if we can get one.

**Comment by JasonGross** [comment]
Ah, is it just pages 11--12 (labeled as 9--10) of https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.90.7205&rep=rep1&type=pdf ?

**Comment by jonsterling** [comment]
@JasonGross Good sleuthing! That's the right one.

**Comment by jonsterling** [comment]
@JasonGross Thomas has obliged to host the note here as well: https://www2.mathematik.tu-darmstadt.de/~streicher/snbe.pdf
